### PR TITLE
Outbreak template pretty

### PR DESCRIPTION
**Pull request by aspina7**
Have made some changes - mostly just visual stuff, added a few functions too for making the basic stuff simpler

### CODE REVIEW

**Comment by zkamvar** [comment]
> Please make the changes to https://github.com/R4EPI/epireports/blob/master/inst/rmarkdown/templates/outbreak/skeleton/skeleton.Rmd. This is the actual template. You used the example file which is just meant for preview on github

I'm going to go ahead and make this change

**Comment by epiamsterdam** [comment]
General comments on the current template (will check markdown tomorrow):
- Column and row labeling for tables: can we try and make these prettier (% instead of prop? or actually proprotion? Can we put the % somewhere to indicate which indicator we are dealing with?
- I dont see suspected cases reflected in the case classification - can this be included
- Can we have a table that classifies cases stratified by sex and age group? Essentially the population pyramid but in a table?
- CFR - can we add a row that calculates the total deaths as part of this table? Without that the proportion calculation is not useful
- Can we add CFR by sex calculation? and CFR by case classification?
- Epi curve: can we add a curve that stratifies by case classification and seperate epi acurves for confirmed cases only, and for suspected cases only?
- Can we add maps by  epi week?
- Can we add chloropleth maps by epi week?

**Comment by dirkschumacher** [comment]
@aspina7 can you add all packages you use in the templates to the suggests section of the `DESCRIPTION` file?

**Comment by dirkschumacher** [comment]
I get the following error when kniting (I have installed that package and I am on Mac OS):
```
Quitting from lines 432-442 (test.Rmd) 
Error: OpenStreetMap package needed for this function to work. Please install it.
In addition: Warning message:
Current projection of mapsub differs from +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0, but is overwritten. 
Execution halted
```

**Comment by aspina7** [comment]
sorry will do this now!

**Comment by epiamsterdam** [comment]
Comments on coding:
-[L27] - i would put this whole section at the top of the markdown. Include list of all packages that shouldbe installed before runnning everything - only after that run the codes around Library
- [L38] - can we include some coding here so that people can visualise their dataset (i.e. 'browse' in STATA?) - i think most people will want to do that. Can we add some coding around exploring the dataset? Number of columns, format of columns, checking for outliers etc.
-[L42] - we will include some example coding for how to clean data, correct?
- [L48] - not sure what this means "TODO: showcase and recommend the linelist package"
-[L50] - should read: # make a copy of your original dataset and name it linelist_cleaned
- [L52] - this assumes you keep the colimn names from your cleaned linelist, yes? can we explain what the epitrix command does?
- [l57] - not clear to me how renaming manually is the same as copying and pasting the existing column names and fixing them?
[L100] - here you mention data cleaning again - but shouldnt we try and keep all the data cleaning in one section at the top?
- [L103] - Error: Error in age_categories(linelist_cleaned$age, breakers = c(0, 5, 10, 30,  : 
  could not find function "age_categories"

**Comment by zkamvar** [comment]
Hi @epiamsterdam, Which file are you commenting on?

**Comment by aspina7** [comment]
@zkamvar sent her rmarkdown script of skeleten (last one i pushed)

**Comment by zkamvar** [comment]
> [L48] - not sure what this means "TODO: showcase and recommend the linelist package" 

That's my job 😬. It's in reference to defining a data dictionary for a data frame https://github.com/reconhub/linelist/issues/2

**Comment by zkamvar** [comment]
> [L103] - Error: Error in age_categories(linelist_cleaned$age, breakers = c(0, 5, 10, 30, :
could not find function "age_categories"

How did you install the package, @epiamsterdam? I was not getting this error. My workflow was:

1. In RStudio, I type: `remotes::install_github("aspina7/epireports@outbreak-template-pretty")`
2. After everything installs, I open up the template through the menus: <kbd>File > New File > R Markdown... </kbd>.
3. Select <kbd> Code > Run Region > Run All </kbd>

**Comment by zkamvar** [comment]
Correction, this should work: `remotes::install_github("R4EPI/epireports#18")`

**Comment by epiamsterdam** [comment]
i installed the functions that Alex emailed me  - can now run the markdown

**Comment by epiamsterdam** [comment]
Comments on Skeleton from Line 100 onwards:
- [L106] - very much like these alternatives for coding included. Means that people will learn slowly how to do data management.
- [L118] - as mentioned - would be good to have the classification suspected, probable and confirmed added here - 
- [L137] - i dont see a column name called 'name' in Linelistcleaned - am i missing something?
- [L182] - can we add extra tables that would allow us to create all the same tables selected single age group or selecting sex or selecting case definition? Can all be in green coding, but that people know how to generate these tables as well
- [L195] - can we add an explanation on why you included the !is.na(sex) code? Could you theoretically produce a pyramid based on casedefinition if you added "!is.na(case_def)"?
- [L217] - as in template - can we add a row for total deaths?
- [L217] - can we add the CFR based on case definition
- [L235] - error: Error in attack_rate(nrow(linelist_cleaned), population, multiplier = 1e+05) : unused argument (multiplier = 1e+05)
- the above error repeats at each attack rate and also mortality rates not working
- I stopped at the mapping as I think Chris is working on this, correct?

**Comment by aspina7** [comment]
Weird. It's a dependency of tmap.

**Comment by dirkschumacher** [comment]
I would suggest that we merge this PR, once @epiamsterdam points have been addressed. Then we can fix smaller issues and code style stuff in a subsequent PR. Otherwise this will just grow too big.

**Comment by epiamsterdam** [comment]
@zkamvar 
> attack_rate()
Error in attack_rate() : could not find function "attack_rate"
> attack_rate
Error: object 'attack_rate' not found

**Comment by epiamsterdam** [comment]
@zkamvar 
> .libPaths()
[1] "C:/rwin/library"                                                        
[2] "\\\\svstor02.msf.oca.int/Homes/Alenglet.OCA/Documents/R/win-library/3.5"

**Comment by aspina7** [comment]
@dirkschumacher - aim to address comments today and tomorrow so we can merge. Chris Jarvis is in Beirut atm with not so much time; I will take a second stab at the mapping comments and then he can update when he has time.

**Comment by aspina7** [comment]
addressing @epiamsterdam  comments. 
> -[L27] - i would put this whole section at the top of the markdown. Include list of all packages that shouldbe installed before runnning everything - only after that run the codes around Library

Alex: True have moved it up - will add bullet with list of packages needed and how to install once finalised

> * [L38] - can we include some coding here so that people can visualise their dataset (i.e. 'browse' in STATA?) - i think most people will want to do that. Can we add some coding around exploring the dataset? Number of columns, format of columns, checking for outliers etc.

Alex: Added a section - its not run in the script - but just demonstrates possibilities with comments

>   -[L42] - we will include some example coding for how to clean data, correct?
> * [L48] - not sure what this means "TODO: showcase and recommend the linelist package"

Alex: Yes, there are some examples of data cleaning - @zkamvar and @thibautjombart are going to chuck in some handy tricks from their new package (called linelist) at some point. 

>   -[L50] - should read: # make a copy of your original dataset and name it linelist_cleaned

Alex: edited 

> * [L52] - this assumes you keep the colimn names from your cleaned linelist, yes? can we explain what the epitrix command does? 

Alex: yes correct - this may change once we use data dictionaries. Have added a short explanation. 

> * [l57] - not clear to me how renaming manually is the same as copying and pasting the existing column names and fixing them? 

Alex: have reworded, is just a way to demonstrate that you can change individual variable names too! 

>   [L100] - here you mention data cleaning again - but shouldnt we try and keep all the data cleaning in one section at the top? 

Alex: This is the correct data cleaning section. The previous section was actually just for correcting variable names. Have changed the wording and titles to reflect this better. 

> * [L103] - Error: Error in age_categories(linelist_cleaned$age, breakers = c(0, 5, 10, 30,  :
>   could not find function "age_categories"

Alex: this will be addressed as we go along and merge this.

**Comment by zkamvar** [comment]
@aspina7, would you like to to fix the merge conflicts created by #28?

**Comment by aspina7** [comment]
in class now and have an exam after. will fix stuff this eve or if not then tomorrow!

**Comment by zkamvar** [comment]
> in class now and have an exam after. will fix stuff this eve or if not then tomorrow!

Oh 💩! I meant would you like **me** to resolve those merge conflicts

**Comment by aspina7** [comment]
replies to @epiamsterdam second bunch of comments 

> * [L106] - very much like these alternatives for coding included. Means that people will learn slowly how to do data management.

:) 
> * [L118] - as mentioned - would be good to have the classification suspected, probable and confirmed added here -

changed it 

> * [L137] - i dont see a column name called 'name' in Linelistcleaned - am i missing something?

no doesnt exist, was just an example. have changed comments to reflect that 

> * [L182] - can we add extra tables that would allow us to create all the same tables selected single age group or selecting sex or selecting case definition? Can all be in green coding, but that people know how to generate these tables as well 

added

@zkamvar  can you do the same magic for descriptive_table as you did for plot_age_pyramid please, here too the zero count factor levels dont show up! 


> * [L195] - can we add an explanation on why you included the !is.na(sex) code? Could you theoretically produce a pyramid based on casedefinition if you added "!is.na(case_def)"?

@zkamvar  I guess with your update to plot_age_pyramid, we no longer need to filter out NAs in advance, right?

> * [L217] - as in template - can we add a row for total deaths?

@dirkschumacher what do you think of adding a totals column to the CFR function ? E.g. to do cfr by groups and then have the overall CFR as bottom row. Better to just do seperately and then bind_rows after? cc @zkamvar 

> * [L217] - can we add the CFR based on case definition 

added 

> * [L235] - error: Error in attack_rate(nrow(linelist_cleaned), population, multiplier = 1e+05) : unused argument (multiplier = 1e+05)
> * the above error repeats at each attack rate and also mortality rates not working

this should be fixed 

> * I stopped at the mapping as I think Chris is working on this, correct?

yep chris is on the case

**Comment by zkamvar** [comment]
> @zkamvar can you do the same magic for descriptive_table as you did for plot_age_pyramid please, here too the zero count factor levels dont show up!

Done  in 533532a

**Comment by zkamvar** [comment]
> >[L195] - can we add an explanation on why you included the !is.na(sex) code? Could you theoretically produce a pyramid based on casedefinition if you added "!is.na(case_def)"?

> @zkamvar I guess with your update to plot_age_pyramid, we no longer need to filter out NAs in advance, right?

I *believe* so. It will be good to actually test this

> @dirkschumacher what do you think of adding a totals column to the CFR function ? E.g. to do cfr by groups and then have the overall CFR as bottom row. Better to just do seperately and then bind_rows after? cc @zkamvar

mebbe

**Comment by aspina7** [comment]
replying to @epiamsterdam General comments 

> * Column and row labeling for tables: can we try and make these prettier (% instead of prop? or actually proprotion? Can we put the % somewhere to indicate which indicator we are dealing with?

changed 

> * I dont see suspected cases reflected in the case classification - can this be included

changed

> * Can we have a table that classifies cases stratified by sex and age group? Essentially the population pyramid but in a table?
done

> * CFR - can we add a row that calculates the total deaths as part of this table? Without that the proportion calculation is not useful

point of discussion as in response to specific code lines above 
"[L217] - as in template - can we add a row for total deaths?
dirkschumacher what do you think of adding a totals column to the CFR function ? E.g. to do cfr by groups and then have the overall CFR as bottom row. Better to just do seperately and then bind_rows after? cc zkamvar"

> * Can we add CFR by sex calculation? and CFR by case classification?

done 

> * Epi curve: can we add a curve that stratifies by case classification and seperate epi acurves for confirmed cases only, and for suspected cases only?

done 

> * Can we add maps by  epi week?
> * Can we add chloropleth maps by epi week?

to be dealt with once mapping has been addressed

**Comment by aspina7** [comment]
replying to @isidro-carrionmartin comments: heeeeey :) 

> •	Attack rate per age group.

will be useful to add this for a dataset where we have age stratified population. Something to add to AJS template? @dirkschumacher 

> •	Smaller age break downs for under 5: in measles outbreak, for example, it would be good to have smaller break down for <5yo (for both AR and total cases), eg. 0 – 5 m, 6-8 m, 9-11m, 12-23m, 2-59 m

This is possible already with the age_categories function, should be implemented in one of the disease specific templates. In general though, dont think it is a good idea to mix months and years within one age category variable ...

> •	Epicurve: would it be useful to also show epicurve by area of origin or health structure of declaration of case? And also by type of case (confirmed, probable, etc)?

have added stratified epicurves, but most often theres too many groupings (not enough colours) to do epicurves by region, so wouldnt add that. But definitely worth supplementing the "place" section as below though.

> •	Cases and attack rate for geographical area: in some contexts we will not have GIS data, maybe good to have some bar graphs for geographical distribution?

agree - have added the attack rate. Not sure a bar chart of that would be super useful though? thoughts @epiamsterdam? 

> •	Data on severity: % admitted? Specific for cholera: level of dehydration?
> •	Distribution of symptoms. 

This we should add to disease specific templates! 

> •	Mortality rate: I wonder if we should try to add the mortality by 10,000 per day, so it can be compared with standard mortality emergency indicators.

Good point this should definitely be added to the function. @zkamvar @dirkschumacher

**Comment by zkamvar** [comment]
Sorry I left a terse "review". I'm being pulled to update the deployer because Thibaut is being deployed. That being said, I don't want to drag this thing out too long. I will merge these changes and make a new PR to update.

**Pull request merged**
